[theme]
primaryColor = "#c756aa"               # azul gobierno sobrio
#primaryColor = "#2C75B2"               # azul gobierno sobrio


backgroundColor = "#e3f2fd"            # gris azulado claro (ni blanco ni oscuro)
#backgroundColor = "#E5E8EC"            # gris azulado claro (ni blanco ni oscuro)
secondaryBackgroundColor = "#E5E8EC"   # gris medio para campos y tarjetas
textColor = "#1E1E1E"                  # gris casi negro
font = "sans serif"
